### ISSUE TITLE
Project components to be completed

### ISSUE THREAD

**Issue by veryvera** [veryvera/plan-calculator#1]
## TODO  :1234: 

*Initial project steps to have a basic plan calculator

* [ ] Convert zip code to corresponding rating area
* [ ] Convert date of birth to age
* [ ] Filter plan options for each family member based on rating area and age
* [ ] Sum each family members rate for each plan to get a family total for each plan
* [ ] Display each Plan showing the family total for the plan
